# Version information.
program_name:       "Fractals"
program_ver:        1.0.0
program_devs:       ["Michael Cvitanovich"]
program_web:        "galacticwingcommander"    
fractal_folder:     "./fractals"
fractal_filename:   "fractal.png"
palette_folder:     "./palettes"
def_palette:        "default.palette"

# Initial Mandlebrot plot.
init_rows:          800
init_cols:          800
init_mid_pt_re:     -0.75
init_mid_pt_im:     0.0
init_pt_div:        0.00375
init_max_its:       100
