# Version information.
program_name:       "Fractals"
program_ver:        0.0.1
program_devs:       ["Michael Cvitanovich"]
program_web:        "galacticwingcommander"    
fractal_folder:      "./fractals"
